# Workflow name
name: 'Storybook Deployment'

# dev branchì— pushë˜ëŠ” ê²½ìš° ë°°í¬
on:
  pull_request:
    branches:
      - dev

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install modules
      - run: |
          yarn install
          yarn chromatic --project-token=${{secrets.CHROMATIC_PROJECT_TOKEN}}
        with:
          exitZeroOnChanges: true
          autoAcceptChanges: true

        #   #ğŸ‘‡ Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
        #   projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      # pr commentë¡œ ìŠ¤í† ë¦¬ë¶ ë°°í¬ ë§í¬ í™•ì¸ ê°€ëŠ¥í•œ ì•¡ì…˜
      - name: comment PR
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: 'ğŸš€storybook: ${{ steps.chromatic.outputs.storybookUrl }}'
