name: Build & Deploy Storybook
on:
  push:
    branches: [dev]
    paths: ['src/stories/**']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build ðŸ”§
        # This needs an Acces Token stored as "GH_TOKEN" ðŸ‘‡
        run: |
          pnpm install
          pnpm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
